language: php

php:
  - '7.2'

install:
  - composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env
  - php artisan key:generate

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE goodwork;'
  - php artisan migrate
  - php artisan passport:install
  - php artisan passport:keys
  - php artisan serve &
  - sleep 5
  - php artisan config:clear

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always