language: php

php:
  - '5.6'
  - '7.0'

install:
  - composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.example .env
  - php artisan key:generate
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE goodwork;'
  - php artisan migrate
  - phantomjs --webdriver=127.0.0.1:9515 &
  - php artisan serve &
  - sleep 5
  - php artisan config:clear

script:
  - vendor/bin/phpunit
  - php artisan dusk

notifications:
  on_success: never
  on_failure: always