language: php

php:
  - '5.6'
  - '7.0'

install:
  - composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.example .env
  - php artisan key:generate

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE goodwork;'
  - php artisan migrate --seed
  - php artisan serve --host=goodwork.local --port=80

script:
  - vendor/bin/phpunit

cache:
  directories:
    - vendor

notifications:
  on_success: never
  on_failure: always