language: php

php:
  - '5.6'
  - '7.0'

install:
  - composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.example .env
  - php artisan key:generate
  - cp .env .env.dusk.local

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE goodwork;'
  - php artisan migrate
  - php artisan serve --host=goodwork.local --port=80 &
  - phantomjs --webdriver=127.0.0.1:4444 &
  - sleep 3

script:
  - vendor/bin/phpunit
  - php artisan dusk

cache:
  directories:
    - vendor

notifications:
  on_success: never
  on_failure: always