[workspace]
resolver = "2"
members = [
    "data",
    "server",
    "views",
]

[workspace.package]
authors = ["Nehal Hasnayeen"]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
chrono = "0.4.23"
