[package]
name = "views"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.11.1", default-features = false, features = ["with-axum"] }
askama_axum = "0.1.0"
