[package]
name = "config"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
serde.workspace = true
lazy_static.workspace = true
serde_yaml = "0.9.16"
